// Tost types
export const SHOW_TOAST_NOFITICATION = "SHOW_TOAST_NOFITICATION";
export const REMOVE_TOAST_NOFITICATION = "REMOVE_TOAST_NOFITICATION";

// Accounts Types
export const SET_SETTING_REQUEST = "SET_SETTING_REQUEST";
